baseURL: "https://finnschule.github.io/" 
title: Finn Sch端le
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 2
        - name: CV
          url: /cv/
          weight: 3
        - name: Blog Posts
          url: /blog/
          weight: 4

params:
    description: "I am PhD student in Economics at Brown University. My research focuses on macroeconomics, monetary policy, and labor markets."
    author: Finn Sch端le
    googleAnalyticsID: "G-V4CLT31NFQ"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","cv","blog-posts"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Finn Sch端le
          subtitle: "I am a **PhD student in Economics at Brown University**. I am a macroeconomist focusing on monetary policy, production networks, and labor markets. **I am on the 2025/26 academic job market.** You can find links to my CV and job market paper below. Before starting graduate school, I worked on monetary policy and public finance as a research assistant at the Brookings Institution. I reveived my M.Sc. in Economics from the University of Warwick and a B.A. in History and Economics from the University of Oxford."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Job-market paper
              url: /papers/jmp/JMP_Finn_Schuele.pdf
            - name: Curriculum vitae
              url: Finn_Schuele_CV.pdf
            - name: Papers
              url: /papers/
            - name: Blog Posts
              url: /blog/

    socialIcons:
        - name: CV
          url: Finn_Schuele_CV.pdf
        - name: Email
          url: mailto:finn_schuele@brown.edu
        - name: GitHub
          url: https://github.com/finnschule
        #- name: Twitter
        #  url: https://x.com/FinnSchule

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Finn Sch端le"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2